version: "3.9"

services:
  btloser_app:
    build: .
    container_name: btloser_app
    ports:
      - "8501:8501"
    volumes:
      - ./app/Newdles:/app/app/Newdles
      - ./app/weekly_rosters:/app/app/weekly_rosters
      - ./app/Availability:/app/app/Availability
    restart: unless-stopped

